"""Initial tables

Revision ID: 040054c6f772
Revises: 
Create Date: 2025-11-12 15:21:44.739950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040054c6f772'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractor',
    sa.Column('detail_code', sa.String(length=32), nullable=False),
    sa.Column('supplier_code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('relationship_start', sa.Date(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contractor_detail_code'), ['detail_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_contractor_supplier_code'), ['supplier_code'], unique=False)

    op.create_table('importbatch',
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('uploaded_by', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importerror',
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('source_file', sa.String(length=128), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['importbatch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoicedetail',
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('detail_code', sa.String(length=32), nullable=True),
    sa.Column('supplier_code', sa.String(length=32), nullable=True),
    sa.Column('invoice_no', sa.String(length=64), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('unit_code', sa.String(length=128), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('item_title', sa.String(length=255), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_number', sa.String(length=64), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('last_update_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.ForeignKeyConstraint(['last_update_batch_id'], ['importbatch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoicedetail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoicedetail_cover_number'), ['cover_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoicedetail_detail_code'), ['detail_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoicedetail_invoice_no'), ['invoice_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoicedetail_supplier_code'), ['supplier_code'], unique=False)

    op.create_table('invoicesummary',
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('detail_code', sa.String(length=32), nullable=True),
    sa.Column('supplier_code', sa.String(length=32), nullable=True),
    sa.Column('automation_number', sa.String(length=64), nullable=True),
    sa.Column('invoice_created_at', sa.Date(), nullable=True),
    sa.Column('delivered_to_accounting_at', sa.Date(), nullable=True),
    sa.Column('delivered_to_supervisor_at', sa.Date(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('cover_number', sa.String(length=64), nullable=True),
    sa.Column('business_owner', sa.String(length=255), nullable=True),
    sa.Column('cost_subject', sa.String(length=255), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('time_span', sa.String(length=128), nullable=True),
    sa.Column('invoice_status', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('contractor_invoice_no', sa.String(length=128), nullable=True),
    sa.Column('permit_number', sa.String(length=128), nullable=True),
    sa.Column('permit_type', sa.String(length=128), nullable=True),
    sa.Column('client_contract_number', sa.String(length=128), nullable=True),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('last_update_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.ForeignKeyConstraint(['last_update_batch_id'], ['importbatch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoicesummary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoicesummary_automation_number'), ['automation_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoicesummary_cover_number'), ['cover_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoicesummary_detail_code'), ['detail_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoicesummary_supplier_code'), ['supplier_code'], unique=False)

    op.create_table('user',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('contractor_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('invoicesummary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoicesummary_supplier_code'))
        batch_op.drop_index(batch_op.f('ix_invoicesummary_detail_code'))
        batch_op.drop_index(batch_op.f('ix_invoicesummary_cover_number'))
        batch_op.drop_index(batch_op.f('ix_invoicesummary_automation_number'))

    op.drop_table('invoicesummary')
    with op.batch_alter_table('invoicedetail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoicedetail_supplier_code'))
        batch_op.drop_index(batch_op.f('ix_invoicedetail_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_invoicedetail_detail_code'))
        batch_op.drop_index(batch_op.f('ix_invoicedetail_cover_number'))

    op.drop_table('invoicedetail')
    op.drop_table('importerror')
    op.drop_table('importbatch')
    with op.batch_alter_table('contractor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contractor_supplier_code'))
        batch_op.drop_index(batch_op.f('ix_contractor_detail_code'))

    op.drop_table('contractor')
    # ### end Alembic commands ###
